#!/usr/bin/python
#
# Author: Sascha Curth
#
import urllib
import json
import sys
import os

scriptname=os.path.basename(__file__)
modulename=scriptname.partition('_')[0]

def initDeviceinfo():
    serial=scriptname.partition('_')[2].partition('.')[0]
    deviceurl = 'http://127.0.0.1:4444/bySerial/%s-%s/api.json' % (modulename,serial)
    deviceresponse = urllib.urlopen(deviceurl)
    devicedata = json.loads(deviceresponse.read())
    return devicedata

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
    #Magic markers for munin autoconf
    #%# family=auto
    #%# capabilities=autoconf suggest
    print "yes"

elif len(sys.argv) == 2 and sys.argv[1] == "suggest":
    huburl = 'http://127.0.0.1:4444/api.json'
    hubresponse = urllib.urlopen(huburl);
    hubdata = json.loads(hubresponse.read())
    for key in hubdata["services"]["yellowPages"]["Temperature"]:
        if "PT100MK1" in key["hardwareId"]:
            serial=key["hardwareId"].partition('-')[2].partition('.')[0]
            print "%s" % serial

elif len(sys.argv) == 2 and sys.argv[1] == "config":
    devicedata=initDeviceinfo()
    print 'graph_title %s' % scriptname
    print 'graph_vlabel temperature in %s' % devicedata["temperature"]["unit"]
    print 'graph_category yoctopuce'
    print 'graph_args --base 1000'

    print 'temp.label %s' % devicedata["temperature"]["unit"]
    print 'temp.draw AREA'
    print 'temp.type GAUGE'

else:
    devicedata=initDeviceinfo()
    print 'temp.value %s' % devicedata["temperature"]["advertisedValue"]

