#!/usr/bin/python
#
# Author: Sascha Curth
#
# sample config
# [YCO2MK01_*]
#   env.carbonDioxide_warning 1300
#   env.carbonDioxide_critical 3000


import urllib
import json
import sys
import os

apiuri='http://127.0.0.1:4444'
scriptname=os.path.basename(__file__)
modulename=scriptname.partition('_')[2].partition('_')[0]
serial=scriptname.partition('_')[2].partition('_')[2].partition('_')[0]
measurementtype=scriptname.partition('_')[2].partition('_')[2].partition('_')[2]

def initDeviceinfo():
    deviceurl = '%s/bySerial/%s-%s/api.json' % (apiuri,modulename,serial)
    deviceresponse = urllib.urlopen(deviceurl)
    devicedata = json.loads(deviceresponse.read())
    return devicedata

if len(sys.argv) == 2 and sys.argv[1] == "autoconf":
    #Magic markers for munin autoconf
    #%# family=auto
    #%# capabilities=autoconf suggest
    print "yes"

elif len(sys.argv) >= 2 and sys.argv[1] == "suggest":
    prefix=''
    suffix=''
    huburl = '%s/api.json' % apiuri
    hubresponse = urllib.urlopen(huburl);
    hubdata = json.loads(hubresponse.read())
    for key in hubdata["services"]["yellowPages"]:
        if key not in ["DataLogger","Network","Relay"]:
            for measurementtype in hubdata["services"]["yellowPages"][key]:
                if len(sys.argv) == 3 and sys.argv[2] == "env":
                    prefix='  env.'
                    print "[%s_%s]" % (scriptname.partition('_')[0],measurementtype["hardwareId"].replace('-','_').replace('.','_'))
                    suffix='.warning 0'
                    print "%s%s%s" % (prefix,measurementtype["hardwareId"].partition('.')[2],suffix)
                    suffix='.critical 0'
                    print "%s%s%s" % (prefix,measurementtype["hardwareId"].partition('.')[2],suffix)
                else:
                    print "%s" % measurementtype["hardwareId"].replace('-','_').replace('.','_')

elif len(sys.argv) == 2 and sys.argv[1] == "config":
    devicedata=initDeviceinfo()
    logicalname=devicedata["module"]["logicalName"]
    print 'graph_title %s %s' % (scriptname,logicalname)
    print 'graph_vlabel %s in %s' % (''.join(measurementtype[0].upper() + measurementtype[1:]),devicedata[measurementtype]["unit"])
    print 'graph_category yoctopuce'

    print '%s.label Current value in %s' % (measurementtype,devicedata[measurementtype]["unit"])
    print '%s.draw LINE1' % measurementtype
    print '%s.type GAUGE' % measurementtype
    for thresholdtype in ["warning","critical"]:
        varname="%s.%s" % (measurementtype,thresholdtype)
        if os.environ.get(varname) is not None:
            print '%s %s' % (varname,os.environ.get(varname))

else:
    devicedata=initDeviceinfo()
    print '%s.value %s' % (measurementtype,devicedata[measurementtype]["advertisedValue"])
